version: '3'
services:
    web:
        build: https://${GITHUB_ACCESS_TOKEN}:@github.com/smilga/analyzer.git#master:web
        environment:
            - API_PORT=${API_PORT}
        command: ["npm", "run", "start"]

    api:
        build: https://${GITHUB_ACCESS_TOKEN}:@github.com/smilga/analyzer.git#master:api
        #- ./api/datastore/mysql/migrations/:/analyzer-api/datastore/mysql/migrations

        environment:
            - API_PORT=${API_PORT}
            - JWT_SECRET=${JWT_SECRET}
        command: ["server"]

    browserless:
        image: browserless/chrome
        restart: always
        environment:
            - MAX_CONCURRENT_SESSIONS=5
            - MAX_QUEUE_LENGTH=0
            - PREBOOT_CHROME=true
            - CONNECTION_TIMEOUT=300000

    nginx:
        image: nginx:latest
        volumes:
            - ./mysite.template:/etc/nginx/conf.d/mysite.template
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=analyzer.dev
            - WEB_PORT=${WEB_PORT}
        command: /bin/bash -c "envsubst '$${NGINX_HOST} $${WEB_PORT}' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
