CREATE TABLE IF NOT EXISTS websites (
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NULL DEFAULT NUll,
    url VARCHAR(255) NOT NULL,
    searched_at DATE NULL DEFAULT NULL,
    created_at DATE NULL DEFAULT NULL,
    deleted_at DATE NULL DEFAULT NULL,
    PRIMARY KEY (id)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
