CREATE TABLE IF NOT EXISTS websites (
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    url VARCHAR(255) NOT NULL,
    inspected_at DATETIME NULL DEFAULT NULL,
    created_at DATETIME NULL DEFAULT NULL,
    deleted_at DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    INDEX (url)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
