FROM golang:1.11.0-alpine3.8

ENV CGO_ENABLED=0

RUN apk update && apk upgrade && \
        apk add --no-cache git && \
        apk add nodejs && \
        apk add nodejs-npm && \
        go get github.com/markbates/refresh

WORKDIR /analyzer-api

