FROM golang:1.12.1-alpine3.9

ENV CGO_ENABLED=0

RUN apk update && apk upgrade && \
        apk add --no-cache git && \
        apk add nodejs && \
        apk add nodejs-npm && \
        go get github.com/markbates/refresh

WORKDIR /analyzer-api
